/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/details`; params?: Router.UnknownInputParams; } | { pathname: `/hotelSwipper`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/hotel/hotelDetails`; params?: Router.UnknownInputParams; } | { pathname: `/place/adventure`; params?: Router.UnknownInputParams; } | { pathname: `/place/cafes`; params?: Router.UnknownInputParams; } | { pathname: `/place/emergency`; params?: Router.UnknownInputParams; } | { pathname: `/place/hotels`; params?: Router.UnknownInputParams; } | { pathname: `/place/tourists`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/details`; params?: Router.UnknownOutputParams; } | { pathname: `/hotelSwipper`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/hotel/hotelDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/place/adventure`; params?: Router.UnknownOutputParams; } | { pathname: `/place/cafes`; params?: Router.UnknownOutputParams; } | { pathname: `/place/emergency`; params?: Router.UnknownOutputParams; } | { pathname: `/place/hotels`; params?: Router.UnknownOutputParams; } | { pathname: `/place/tourists`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/details${`?${string}` | `#${string}` | ''}` | `/hotelSwipper${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/hotel/hotelDetails${`?${string}` | `#${string}` | ''}` | `/place/adventure${`?${string}` | `#${string}` | ''}` | `/place/cafes${`?${string}` | `#${string}` | ''}` | `/place/emergency${`?${string}` | `#${string}` | ''}` | `/place/hotels${`?${string}` | `#${string}` | ''}` | `/place/tourists${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/details`; params?: Router.UnknownInputParams; } | { pathname: `/hotelSwipper`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/hotel/hotelDetails`; params?: Router.UnknownInputParams; } | { pathname: `/place/adventure`; params?: Router.UnknownInputParams; } | { pathname: `/place/cafes`; params?: Router.UnknownInputParams; } | { pathname: `/place/emergency`; params?: Router.UnknownInputParams; } | { pathname: `/place/hotels`; params?: Router.UnknownInputParams; } | { pathname: `/place/tourists`; params?: Router.UnknownInputParams; };
    }
  }
}
